Repository openchatai/OpenCopilot, pull requests merged in 2023-11, with the labels that each got.

#221 Falta/widget enhancments 2
  copilot-widget/lib/components/ChatHeader.tsx
  copilot-widget/lib/components/ChatInputFooter.tsx
  copilot-widget/lib/components/Messages.tsx
  copilot-widget/lib/contexts/Controller.tsx
  copilot-widget/lib/contexts/InitialDataContext.tsx
  copilot-widget/lib/hooks/useCopy.ts
  copilot-widget/lib/screens/ChatScreen.tsx
  copilot-widget/lib/types/messageTypes.ts
  copilot-widget/lib/utils/utils.ts
  copilot-widget/tailwind.config.ts
Labels: 🌠 Enhancement

#233 Widget/user obj
  backend/public/pilot.js
  copilot-widget/index.html
  copilot-widget/lib/components/Messages.tsx
  copilot-widget/lib/components/ToolTip.tsx
  copilot-widget/lib/contexts/ConfigData.tsx
  copilot-widget/lib/contexts/Controller.tsx
  copilot-widget/lib/types/options.ts
  copilot-widget/package.json
Labels: Hotfix

#240 Adding code for resuming website scraping
  llm-server/requirements.txt
  llm-server/routes/uploads/celery_service.py
  llm-server/routes/uploads/upload_controller.py
  workers/repos/pdf_data_sources.py
  workers/repos/website_data_sources.py
  workers/shared/models/opencopilot_db/pdf_data_source_model.py
  workers/shared/models/opencopilot_db/website_data_source.py
  workers/shared/models/setup.py
  workers/tasks/process_pdfs.py
  workers/tasks/web_crawl.py
Labels: dev test complete

#213 Add knowledge base layout and components
  backend/public/pilot.js
  copilot-widget/index.html
  copilot-widget/lib/components/Messages.tsx
  copilot-widget/lib/components/ToolTip.tsx
  copilot-widget/lib/contexts/ConfigData.tsx
  copilot-widget/lib/contexts/Controller.tsx
  copilot-widget/lib/types/options.ts
  copilot-widget/package.json
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/AddDataSource.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/KnowledgeTable.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/SearchBox.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/searchAtom.ts
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/layout.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/page.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/layout.tsx
  dashboard/components/ui/checkbox.tsx
  dashboard/components/ui/dialog.tsx
  dashboard/components/ui/hover-card.tsx
  dashboard/components/ui/input.tsx
  dashboard/components/ui/table.tsx
  dashboard/components/ui/textarea.tsx
  dashboard/data/knowledge.ts
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  dashboard/tailwind.config.js
Labels: work in progress

#259 Feat/model support
  docker-compose.yml
  k8s/backend-deployment.yaml
  k8s/dashboard-deployment.yaml
  k8s/llm-server-deployment.yaml
  k8s/workers-deployment.yaml
  llm-server/routes/root_service.py
  llm-server/routes/workflow/extractors/convert_json_to_text.py
  llm-server/routes/workflow/extractors/extract_body.py
  llm-server/routes/workflow/extractors/extract_param.py
  llm-server/routes/workflow/extractors/transform_api_response.py
  llm-server/routes/workflow/utils/__init__.py
  llm-server/routes/workflow/utils/detect_multiple_intents.py
  llm-server/routes/workflow/utils/router.py
  llm-server/utils/chat_models.py
  llm-server/utils/get_chat_model.py
Labels: do not merge

#264 Staging
  _swaggers/guild_quality.json
  backend/public/pilot.js
  backend/routes/api.php
  copilot-widget/index.html
  copilot-widget/lib/contexts/ConfigData.tsx
  copilot-widget/lib/contexts/Controller.tsx
  copilot-widget/lib/contexts/WidgetState.tsx
  copilot-widget/lib/types/options.ts
  copilot-widget/package.json
  dashboard/app/(copilot)/copilot/[copilot_id]/CopilotWidget.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/_parts/ChatScreen.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/_parts/ConversationAside.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/_parts/ConversationHeader.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/_parts/ListConverations.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/_parts/atoms.ts
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/layout.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/conversations/page.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/AddDataSource.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/KnowledgeTable.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/page.tsx
  dashboard/app/globals.css
  dashboard/components/ui/avatar.tsx
  dashboard/components/ui/popover.tsx
  dashboard/data/conversations.ts
  dashboard/data/knowledge.ts
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  docker-compose.yml
  k8s/backend-deployment.yaml
  k8s/dashboard-deployment.yaml
  k8s/llm-server-deployment.yaml
  k8s/workers-deployment.yaml
  llm-server/app.py
  llm-server/models/repository/chat_history_repo.py
  llm-server/requirements.txt
  llm-server/routes/_swagger/controller.py
  llm-server/routes/chat/chat_controller.py
  llm-server/routes/root_service.py
  llm-server/routes/workflow/extractors/convert_json_to_text.py
  llm-server/routes/workflow/extractors/extract_body.py
  llm-server/routes/workflow/extractors/extract_param.py
  llm-server/routes/workflow/extractors/transform_api_response.py
  llm-server/routes/workflow/utils/__init__.py
  llm-server/routes/workflow/utils/detect_multiple_intents.py
  llm-server/routes/workflow/utils/router.py
  llm-server/routes/workflow/utils/run_openapi_ops.py
  llm-server/utils/chat_models.py
  llm-server/utils/get_chat_model.py
  llm-server/utils/vector_db/add_workflow.py
  llm-server/utils/vector_store_setup.py
  nginx/nginx.conf
  workers/shared/utils/opencopilot_utils/get_vector_store.py
  workers/shared/utils/opencopilot_utils/init_vector_store.py
  workers/shared/utils/opencopilot_utils/interfaces.py
  workers/shared/utils/setup.py
  workers/tasks/process_markdown.py
  workers/tasks/process_pdfs.py
  workers/tasks/web_crawl.py
Labels: Hotfix

#285 Dashboard/router events
  README.md
  dashboard/app/(copilot)/_parts/LogoMenu.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/flows/_parts/WorkflowsList.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/flows/layout.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/_parts/KnowledgeTable.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/knowledge/layout.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/layout.tsx
  dashboard/app/(copilot)/copilot/[copilot_id]/page.tsx
  dashboard/app/(main)/_parts/Aside.tsx
  dashboard/app/(main)/_parts/CopilotsContainer.tsx
  dashboard/app/(main)/_parts/SearchModal.tsx
  dashboard/app/(main)/create/copilot/_parts/ValidateSwaggerStep.tsx
  dashboard/app/(main)/create/copilot/page.tsx
  dashboard/app/(main)/page.tsx
  dashboard/app/layout.tsx
  dashboard/components/ui/NavLink.tsx
  dashboard/data/conversations.ts
  dashboard/data/flow.ts
  dashboard/data/knowledge.ts
  dashboard/lib/Toploader.tsx
  dashboard/lib/router-events/events.ts
  dashboard/lib/router-events/index.ts
  dashboard/lib/router-events/patch-router/link.tsx
  dashboard/lib/router-events/patch-router/router.ts
  dashboard/lib/router-events/patch-router/should-trigger-start-event.ts
  dashboard/lib/router-events/wrapper.tsx
  dashboard/package.json
  dashboard/pnpm-lock.yaml
  llm-server/.env.example
  llm-server/app.py
  llm-server/requirements.txt
  llm-server/routes/workflow/workflow_controller.py
  nginx/nginx.conf
  nginx/nginx_k8s.conf
  requirements.txt
  workers/requirements.txt
Labels: 🌠 Enhancement

#298 Confetti when new Copilot is Created
  dashboard/app/(main)/create/copilot/page.tsx
  dashboard/app/_store/atoms/confetti.ts
  dashboard/app/layout.tsx
  dashboard/components/domain/confetti-canvas.tsx
  dashboard/package.json
  dashboard/pnpm-lock.yaml
Labels: easter-egg
